[package]
name = "html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.1"
pest_derive = "2.5.1"

[dev-dependencies]
static_init = "1.0.3"